package Model.Localisation;

public enum LocalisationType
{
    PROVINCE_LOCALITATION,
    AREA_LOCALITATION,
    REGION_LOCALITATION,
    SUPERREGION_LOCALITATION,
    CONTINENT_LOCALITATION,
    TRADENODE_LOCALITATION,
}
